<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Admin 

{

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $id;

	/**
	 * 
	 * @var varchar
	 * @access protected
	 */
	protected  $pseudo;

	/**
	 * 
	 * @var varchar
	 * @access protected
	 */
	protected  $pass;


	public function __construct(array $donnees)

	{
		
		$this->hydrate($donnees);
		
	}

	public function hydrate(array $donnees)

	{

	  foreach ($donnees as $key => $value)

	  {
	    
	    $method = 'set'.ucfirst($key);
	        
	    
	    if (method_exists($this, $method))

	    {
	      
	      $this->$method($value);

	    }
	  }
	}

	public function getId()

	{

		return $this->id;

	}

	public function getPseudo()

	{

		return $this->pseudo;

	}

	public function getPass()

	{

		return $this->pass;

	}

	public function setId($id)

	{

		$id = (int) $id;

        if ($id > 0)

    	{

     		$this->id = $id;

		}

	}

	public function setPseudo($pseudo)

	{

		if (is_string($pseudo))

    	{

      		$this->pseudo = $pseudo;

    	}

	}

	public function setPass($pass)

	{

		if (is_string($pass))

    	{

      		$this->pass = $pass;

    	}

	}


}
?>