<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Manager
 */
require_once('Manager.class.php');

class CommentManager extends Manager 

{

	
	/**
	 * @access public
	 */

	public function getListComments($postId, $state) 

	{

		$listComments = [];

		$q = $this->db->prepare('SELECT id, author, comment, DATE_FORMAT(comment_date, \'%d/%m/%Y à %Hh%imin%ss\') AS comment_date_fr FROM comments WHERE post_id = ? AND state = ? ORDER BY comment_date DESC');

		$q->execute(array($postId, $state));

        while ($donnees = $q->fetch(PDO::FETCH_ASSOC))

    	{

      		$listComments[] = new Comment($donnees);

   		}

    	return $listComments;

	}


	/**
	 * @access public
	 */

	public function getComment($commentId) 

	{

	    $comment = $this->db->prepare('SELECT id, post_id, author, comment, DATE_FORMAT(comment_date, \'%d/%m/%Y à %Hh%imin%ss\') AS comment_date_fr FROM comments WHERE id = ?');

        $comment->execute(array($commentId));

        $comment = $comment->fetch(PDO::FETCH_ASSOC);

        $commentObject = new Comment($comment);

        return $commentObject;

	}


	/**
	 * @access public
	 */

	public function modifyComment(Comment $comment) 

	{

		$modifyedComment = $this->db->prepare('UPDATE comments SET author = :author, comment = :comment, state = :state, comment_date = NOW() WHERE id = :id');

		$modifyedComment->bindValue(':author', $comment->author(), PDO::PARAM_VARCHAR);
		$modifyedComment->bindValue(':comment', $comment->comment(), PDO::PARAM_TEXT);
		$modifyedComment->bindValue(':state', $comment->state(), PDO::PARAM_BOOL);
		$modifyedComment->bindValue(':id', $comment->id(), PDO::PARAM_INT);

		$modifyedComment->execute();

	}


	
	/**
	 * @access public
	 */

	public function addComment(Comment $comment) 

	{

		$newComment = $this->db->prepare('INSERT INTO comments(post_id, author, comment, comment_date) VALUES(:post_id, :author, :comment, NOW())');

        $newComment->bindValue(':post_id', $comment->post_id(), PDO::PARAM_INT);
        $newComment->bindValue(':author', $comment->author(), PDO::PARAM_VARCHAR);
		$newComment->bindValue(':comment', $comment->comment(), PDO::PARAM_TEXT);
		
		$newComment->execute();

	}

	
	


}
?>