<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Manager 

{

  protected $db; // Instance de PDO
  
  public function __construct()

  {

    $this->setDb($this->dbConnect());
    
  }

  protected function dbConnect()

  {

    try

    {

        $db = new PDO('mysql:host=localhost;dbname=blog_ecrivain;charset=utf8', 'root', '');
    }
        
    catch (Exception $e)

    {

        die('Erreur : ' . $e->getMessage());

    }
    
    return $db;

  }

  public function setDb(PDO $db)

  {

    $this->db = $db;

  }

}

?>