<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Manager
 */
require_once('Manager.class.php');

class PostManager extends Manager 

{
	

	/**
	 * @access public
	 */

	public function getListPosts($state = PUBLISHED) 

	{

		$listPosts = [];

		$q = $this->db->prepare('SELECT id, title, content, DATE_FORMAT(creation_date, \'%d/%m/%Y à %Hh%imin%ss\') AS creationDate, state FROM posts WHERE state = :state ORDER BY creation_date DESC');

		$q->bindValue(':state', $state);

		$q->execute();


        while ($donnees = $q->fetch(PDO::FETCH_ASSOC))

    	{

      		$listPosts[] = new Post($donnees);

   		}

        return $listPosts;

	}


	/**
	 * @access public
	 */

	public function getPost($id) 

	{

		$post = $this->db->prepare('SELECT id, title, content, DATE_FORMAT(creation_date, \'%d/%m/%Y à %Hh%imin%ss\') AS creation_date_fr FROM posts WHERE id = ?');

        $post->execute(array($id));

        $post = $post->fetch(PDO::FETCH_ASSOC);

        $postObject = new Post($post);

        return $postObject;

	}


	/**
	 * @access public
	 */

	public function modifyPost(Post $post) 

	{

		$updatedPost = $this->db->prepare('UPDATE posts SET title = :title, content = :content, state = :state, creation_date = NOW() WHERE id = :id');

        $updatedPost->bindValue(':title', $post->title(), PDO::PARAM_VARCHAR);
		$updatedPost->bindValue(':content', $post->content(), PDO::PARAM_TEXT);
		$updatedPost->bindValue(':state', $post->state(), PDO::PARAM_BOOL);
		$updatedPost->bindValue(':id', $post->id(), PDO::PARAM_INT);

		$updatedPost->execute();

	}


	/**
	 * @access public
	 */

	public function addPost(Post $post) 

	{

		$addPost = $this->db->prepare('INSERT INTO posts(title, content, state, creation_date) VALUES(:title, :content, :state, NOW())');

        $addPost->bindValue(':title', $post->title(), PDO::PARAM_VARCHAR);
		$addPost->bindValue(':content', $post->content(), PDO::PARAM_TEXT);
		$addPost->bindValue(':state', $post->state(), PDO::PARAM_BOOL);
		
		$addPost->execute();

	}


	
}
?>