<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Manager
 */
require_once('Manager.class.php');

class AdminManager extends Manager 

{


	/**
	 * @access public
	 * @param pdo $db 
	 * @return void
	 */

	private $_db; // Instance de PDO
  
  	public function __construct($db)

  	{

   	 	$this->setDb($db);
    
  	}

 	public function setDb(PDO $db)

  	{

  		$this->_db = $db;

  	}

  	public function connect($pseudo, $pass)

  	{
  		
  	}


}
?>