<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Manager
 */
require_once('Manager.class.php');

class CommentManager extends Manager 

{

	private $_db; // Instance de PDO
  
  	public function __construct($db)

  	{

   	 	$this->setDb($db);
    
  	}

	/**
	 * @access public
	 */

	public function getListComments($postId) 

	{

	}


	/**
	 * @access public
	 */

	public function getComment($commentId) 

	{

	}


	/**
	 * @access public
	 */

	public function modifyComment($id, $author, $comment) 

	{

	}


	/**
	 * @access public
	 */

	public function deleteComment($commentId) 

	{

	}


	/**
	 * @access public
	 */

	public function addComment($pseudo, $comment) 

	{

	}


	/**
	 * @access public
	 */

	public function addCommentForm() 

	{

	}


	public function setDb(PDO $db)

  	{

  		$this->_db = $db;

  	}


}
?>