<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Manager 

{

	protected function dbConnect()

    {
		try

		{

        	$db = new PDO('mysql:host=localhost;dbname=test;charset=utf8', 'root', '');
		}
        
		catch (Exception $e)

		{

        die('Erreur : ' . $e->getMessage());

		}
		
		return $db;
    }


}
?>