<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Manager
 */
require_once('Manager.class.php');

class PostManager extends Manager 

{
	private $_db; // Instance de PDO
  
  	public function __construct($db)

 	{

    	$this->setDb($db);

  	}

	


	/**
	 * @access public
	 */

	public function getListPosts() 

	{

		$db = $this->dbConnect();

        $req = $db->query('SELECT id, title, content, DATE_FORMAT(creation_date, \'%d/%m/%Y à %Hh%imin%ss\') AS creation_date_fr, state FROM posts WHERE state=? ORDER BY creation_date DESC LIMIT 0, 5');


        return $req;

	}


	/**
	 * @access public
	 */

	public function getPost($postId) 

	{

	}


	/**
	 * @access public
	 */

	public function modifyPost($postId, $title, $content) 

	{

	}


	/**
	 * @access public
	 */

	public function publishPost($title, $content) 

	{

	}


	/**
	 * @access public
	 */

	public function draftPost($title, $content) 

	{

	}


	public function setDb(PDO $db)

  	{

    	$this->_db = $db;

  	}


}
?>